version: "3"
# 管理的服务
services:
  article:
    # 指定镜像
    image: registry.cn-chengdu.aliyuncs.com/qinjie/graduation_project_roger_article:latest
    container_name: article
    ports:
      # 端口映射
      - 30008:30008
    restart: always
  gateway:
    # 指定镜像
    image: registry.cn-chengdu.aliyuncs.com/qinjie/graduation_project_roger_gateway:latest
    container_name: gateway
    ports:
      # 端口映射
      - 30004:30004
    restart: always
  authority:
    # 指定镜像
    image: registry.cn-chengdu.aliyuncs.com/qinjie/graduation_project_roger_authority:latest
    container_name: authority
    ports:
      # 端口映射
      - 30005:30005
    restart: always